[package]
name = "ProcessorInfo"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.57.0", features = ["Wdk_System_SystemInformation", "Win32_System", "Win32_System_SystemInformation"] }
windows-sys = "0.52.0"
